pub const ORB_MAX_COUNT: usize = 3;
pub const ORB_MAX_RADIUS: f32 = 42.0;
pub const ORB_COLLECTION_TIME: f32 = 0.4;
pub const ORB_COLLECTION_POWER: f32 = 2.0;

pub const EXAMPLE_PATROLLER_SQUARE_DURATION: f32 = 1.0;
pub const EXAMPLE_PATROLLER_DIAGON_DURATION: f32 = 2.0;

pub const MULTIPLIER_WHEN_SLOW_MOTION: f32 = 0.05;
pub const SLOW_MOTION_KICK_IN_AND_OUT_TIME: f32 = 0.2;

pub const INITIAL_MONSTERS_AMOUNT: i32 = 3;
pub const Z_LAYER_MONSTER: f32 = 9.0;

pub const PLAYER_MOVEMENT_DELTA: f32 = 4.0;
pub const Z_LAYER_PLAYER: f32 = 10.0;

pub const PLAYER_BOMB_PICKING_RANGE: f32 = 24.0;
