use bevy::math::Vec3;

pub const BOMB_SPAWNING_ATTEMPTS: usize = 42;
pub const BOMB_SAFE_RADIUS: f32 = 20.0;
pub const Z_LAYER_BOMB: f32 = 8.0;
pub const Z_LAYER_BOMB_EXPLOSION: f32 = 7.0;
pub const Z_LAYER_FLOOR_HOLE: f32 = 6.0;

pub const TIME_IT_TAKES_BOMB_TO_GROW: f32 = 0.3;
pub const BOMB_SIZE: f32 = 24.0;
pub const BOMB_SPAWN_SCALE: f32 = 0.01;

pub const BOMB_MAX_TIME: usize = 7;
pub const BOMB_MIN_TIME: usize = 4;

pub const BOMB_TIME_LEFT_FONT_SIZE: f32 = 26.0;
pub const BOMB_THROWING_SPEED: f32 = 2000.0;

pub const BOMB_EXPLOSION_RADIUS: f32 = 140.0; //MUST BE LESS THAN ALL MONSTER HEARING DISTANCES
pub const BOMB_BLAST_FACTOR: f32 = 5000.0;
pub const POST_BOMB_HIT_DESPAWN_TIME: f32 = 0.08;

pub const ABOUT_TO_EXPLODE_TIME_CIEL: usize = 3;

pub const BOMB_SPAWN_INITIAL_INTERVAL: f32 = 5.0;
pub const BOMB_SPAWN_INTERVAL_DELTA: f32 = 0.3;
pub const BOMB_SPAWN_MINIMAL_INTERVAL: f32 = 1.1;

pub const MAX_BOMB_COUNT: usize = 20;

pub const BOMB_NORMAL_LIGHT_INTENSITY: f32 = 1.0;
pub const BOMB_ABOUT_TO_EXPLODE_LIGHT_INTENSITY: f32 = 6.0;
pub const EXPLOSION_PREVIEW_LIGHT_INTENSITY: f32 = 10.0;

pub const BOMB_SPAWN_LOCATION_ON_MENU: Vec3 = Vec3::new(30.0, 30.0, Z_LAYER_BOMB);
