pub const INITIAL_MONSTERS_AMOUNT: i32 = 3;
pub const MONSTER_SPAWNING_ATTEMPTS: usize = 32;
pub const MONSTER_SAFE_RADIUS: f32 = 32.0;
pub const MONSTER_FULL_SIZE: f32 = 32.0;
pub const MONSTER_COLLIDER_RADIUS: f32 = 24.0;
pub const Z_LAYER_MONSTER: f32 = 12.0;

pub const TIME_IT_TAKES_MONSTERS_TO_SPAWN: f32 = 3.0;
pub const MONSTER_FADED_ALPHA: f32 = 0.8;
pub const MONSTER_SIZE_WHEN_CHASING: f32 = 4.2;
pub const MONSTER_COLLIDER_RADIUS_FACTOR_WHEN_CHASING: f32 = 10.0;
pub const MONSTER_CHASE_START_VISUAL_CHANGE_DURATION: f32 = 0.5;

pub const MONSTER_SPEED_WHEN_CHASING: f32 = 20.0;
pub const MONSTER_SPEED_WHEN_FLEEING: f32 = 70.0;

pub const FLYING_FRAME_LOOP_DURATION: f32 = 0.16;

pub const MONSTER_MAX_PATH_VERTICES: usize = 12;

pub const MONSTER_SPAWN_INITIAL_INTERVAL: f32 = 4.0;
pub const MONSTER_SPAWN_INTERVAL_DELTA: f32 = 0.3;
pub const MONSTER_SPAWN_MINIMAL_INTERVAL: f32 = 1.0;

pub const MAX_MONSTER_COUNT: usize = 18;

pub const MONSTER_LIGHT_INTENSITY_NORMAL: f32 = 2.0;
pub const MONSTER_LIGHT_INTENSITY_CHASING: f32 = 4.2;
pub const MONSTER_LIGHT_FALLOFF: f32 = 2.0;
pub const MONSTER_PHANTOM_LIGHT_FALLOFF: f32 = 4.0;
