pub const INITIAL_MONSTERS_AMOUNT: i32 = 3;
pub const MONSTER_SPAWNING_ATTEMPTS: usize = 32;
pub const MONSTER_SAFE_RADIUS: f32 = 32.0;
pub const MONSTER_SPAWN_INTERVAL: f32 = 11.0;
pub const MONSTER_FULL_SIZE: f32 = 32.0;
pub const MONSTER_COLLIDER_RADIUS: f32 = 40.0;
pub const Z_LAYER_MONSTER: f32 = 12.0;

pub const TIME_IT_TAKES_MONSTERS_TO_SPAWN: f32 = 2.0;
pub const MONSTER_FADED_ALPHA: f32 = 0.8;
pub const MONSTER_SIZE_WHEN_CHASING: f32 = 4.2;
pub const MONSTER_CHASE_START_VISUAL_CHANGE_DURATION: f32 = 0.5;

pub const MONSTER_SPEED_WHEN_CHASING: f32 = 20.0;
pub const MONSTER_SPEED_WHEN_FLEEING: f32 = 70.0;
